language: php

# We want to test against PHP 5.3/5.4/5.5
php:
  - 5.5
  - 5.4
  - 5.3
#  - 5.6
#  - hhvm

# Separate different test suites
env:
  matrix:
    # PDO Mysql
    - TEST_SUITE=IntegrationTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=CoreTests MYSQL_ADAPTER=PDO_MYSQL
    # Mysqli
    - TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    # Javascript tests
    - TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
  global:
    - secure: "AMhZmPZx4SUcuZRBzGHlQPxzM4D8FvFB3UThDa52gbi9KIBrwcumzV2VGi6B\n5fgjwtB4XTE1In7qhY2HMikPWBmWYYOQ5QcMPJsqqHt4iMmahx8WKzne6NOk\nNpqAuje/fulNGeP2LJZi0nrub3Fh4VwXaOvpNloKNQN/2JuqPtM="
    - secure: "DySde80fX3dw0osGY5s5lGiGLjMleUkkONsuRDC4xjT1hAQP94FGHpPXVZV8\nAQY0s8MQmcK2eRLOQrmE9Bh1XXbGqh40s66XhSWq0hulFHxQH5OLaZXccFeu\n5WxGkHXnNDIc+CVhXW/IIbHZPO1K6hffS8fuvP1o6mYgxwFL6Xw="

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
  exclude:
    # Javascript tests need to run only on one PHP version
    - php: 5.4
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.5
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.6
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: hhvm
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    # AngularJS tests need to run only on one PHP version
    - php: 5.4
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.5
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.6
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: hhvm
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    # Only run Mysqli tests on PHP 5.5
    - php: 5.4
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.4
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.4
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI

script: ./travis.sh

before_script:
  - ./tests/travis/before_script.sh

after_success:
  - ./tests/travis/after_success.sh

after_script:
  - ./tests/travis/after_script.sh

notifications:
  slack:
    rooms:
      - piwik:3HWhNh21qPfDACQXTrJOb0mW
      - piwikpro:7OABSbDrywSTo2nv9lD2svXG

  irc:
    skip_join: true
    on_success: change
    channels:
      - "irc.freenode.org#piwik-dev"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
  #email:
  # if we specify piwik-builds@piwik.org then the developer doesn't get notified
  #  - piwik-builds@piwik.org
  # this is a missing feature by Travis to notify both list and committer
